ALTER TYPE "Subject" ADD VALUE 'BIOLOGY';
ALTER TYPE "Subject" ADD VALUE 'CHEMISTRY';
ALTER TYPE "Subject" ADD VALUE 'ICT';
ALTER TYPE "Subject" ADD VALUE 'PHYSICS';
ALTER TYPE "Subject" ADD VALUE 'PSYCHOLOGY';
ALTER TYPE "Subject" ADD VALUE 'SOCIOLOGY';
ALTER TYPE "Subject" ADD VALUE 'SPANISH';

ALTER TABLE "ChildProfile" ADD COLUMN "subjects" "Subject"[] NOT NULL DEFAULT ARRAY[]::"Subject"[];
